apiVersion: v1
kind: PersistentVolume #actual storage infra (wsl data directory)
metadata:
  name: fraud-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data #the mnt/d/...frud-detectiontion/data was no available inside minikube ssh (VM), so I used the wsl data directory which is accessible and shared with minikube)
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim #request for storage that pods use
metadata:
  name: fraud-data-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can read
  resources:
    requests:
      storage: 5Gi  # Adjust based on your data size
  storageClassName: standard  # Minikube's default storage class
  volumeName: fraud-data-pv
