apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: airflow
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: fraud-detection-streamlit:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service.airflow.svc.cluster.local:5000"
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: mlflow-artifacts
          mountPath: /mlflow
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fraud-data-pvc
      - name: mlflow-artifacts
        persistentVolumeClaim:
          claimName: mlflow-pvc
